# Generated by Django 5.0.6 on 2024-09-07 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_otpcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_img',
            field=models.TextField(blank=True, null=True),
        ),
    ]
