# Generated by Django 5.0.6 on 2024-09-09 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='next_stage',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='stage_text',
        ),
        migrations.AddField(
            model_name='stage',
            name='description',
            field=models.TextField(default='No description provided'),
        ),
        migrations.AddField(
            model_name='stage',
            name='stage_number',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_option',
            field=models.CharField(max_length=255),
        ),
    ]
