# Generated by Django 5.0.6 on 2024-09-09 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_remove_stage_next_stage_remove_stage_stage_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='description',
        ),
        migrations.AddField(
            model_name='stage',
            name='correct_option',
            field=models.CharField(default=1, max_length=255),
        ),
        migrations.AddField(
            model_name='stage',
            name='option1',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='stage',
            name='option2',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='stage',
            name='option3',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='stage',
            name='option4',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_option',
            field=models.CharField(default=1, max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='option1',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='option2',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='option3',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='option4',
            field=models.CharField(default='', max_length=255),
        ),
    ]
