# Generated by Django 5.0.6 on 2024-09-13 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_remove_stage_description_stage_correct_option_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='option1',
            new_name='option1_title',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='option2',
            new_name='option2_title',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='option3',
            new_name='option3_title',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='option4',
            new_name='option4_title',
        ),
        migrations.RenameField(
            model_name='stage',
            old_name='option1',
            new_name='option1_title',
        ),
        migrations.RenameField(
            model_name='stage',
            old_name='option2',
            new_name='option2_title',
        ),
        migrations.RenameField(
            model_name='stage',
            old_name='option3',
            new_name='option3_title',
        ),
        migrations.RenameField(
            model_name='stage',
            old_name='option4',
            new_name='option4_title',
        ),
        migrations.AddField(
            model_name='question',
            name='option1_image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='option2_image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='option3_image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='option4_image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stage',
            name='option1_image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stage',
            name='option2_image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stage',
            name='option3_image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stage',
            name='option4_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
