# Generated by Django 5.0.6 on 2024-09-13 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_rename_option1_question_option1_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='option1_test_image',
            field=models.ImageField(default=1, upload_to=''),
        ),
    ]
