# Generated by Django 5.0.6 on 2024-09-24 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0012_question_description_question_difficulty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='option1_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='stage',
            name='option2_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='stage',
            name='option3_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='stage',
            name='option4_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
