# Generated by Django 5.0.6 on 2024-09-25 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0013_alter_stage_option1_image_alter_stage_option2_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stage',
            old_name='option1_image_basa64',
            new_name='option1_image_base64',
        ),
        migrations.RenameField(
            model_name='stage',
            old_name='option2_image_basa64',
            new_name='option2_image_base64',
        ),
        migrations.RenameField(
            model_name='stage',
            old_name='option3_image_basa64',
            new_name='option3_image_base64',
        ),
        migrations.RenameField(
            model_name='stage',
            old_name='option4_image_basa64',
            new_name='option4_image_base64',
        ),
        migrations.AlterField(
            model_name='stage',
            name='correct_option',
            field=models.CharField(default='1', max_length=255),
        ),
    ]
