# Generated by Django 5.0.6 on 2024-09-25 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0014_rename_option1_image_basa64_stage_option1_image_base64_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='img_base64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
