# Generated by Django 5.0.6 on 2024-10-06 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0016_stage_option1_descrption_stage_option2_descrption_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='option1_image',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='option2_image',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='option3_image',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='option4_image',
        ),
    ]
