# Generated by Django 5.0.6 on 2024-10-06 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0017_remove_stage_option1_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='img_base64',
            new_name='question_latex',
        ),
        migrations.RenameField(
            model_name='stage',
            old_name='option1_image_base64',
            new_name='option1_latex',
        ),
        migrations.RenameField(
            model_name='stage',
            old_name='option2_image_base64',
            new_name='option2_latex',
        ),
        migrations.RenameField(
            model_name='stage',
            old_name='option3_image_base64',
            new_name='option3_latex',
        ),
        migrations.RenameField(
            model_name='stage',
            old_name='option4_image_base64',
            new_name='option4_latex',
        ),
        migrations.RemoveField(
            model_name='question',
            name='img',
        ),
    ]
